

export const roomdata = [
        {
            id:1,
            imgs: 'roomOne',
            title: 'Suite A',
            Suite: 'Suite A',
            titletext: 'Our Suite A offers breathtaking views of the city skyline',
            firstlisttext: 'Size: 280sq ft',
            secondlisttext: 'Beds: 2 Doubles(s)',
            roomSize: '280sq ft',
            bed: '2 Doubles(s)',
            icon: '/Images/i.png',
            icon1: '/Images/i0.png',
            icon2: '/Images/i1.png',
            icon3: '/Images/i2.png',
            icon4: '/Images/i3.png',
            icon5: '/Images/i4.png',
            icon6: '/Images/i5.png',
            price: '$250',
            buttontext: 'MORE INFO',
            link: '/suiteone'
        },

        {
            id:2,
            imgs: 'roomTwo',
            title: 'Suite B',
            Suite: 'Suite B',
            titletext: 'Our Suite A offers breathtaking views of the city skyline',
            firstlisttext: 'Size: 240sq ft',
            secondlisttext: 'Beds: 1 king(s)',
            roomSize: '240sq ft',
            bed: '1 king(s)',
            icon: '/Images/i.png',
            icon1: '/Images/i0.png',
            icon2: '/Images/i1.png',
            icon3: '/Images/i2.png',
            icon4: '/Images/i3.png',
            icon5: '/Images/i4.png',
            icon6: '/Images/i5.png',
            price: '$275',
            buttontext: 'MORE INFO',
            link: '/suitetwo'
        },

        {
            id:3,
            imgs: 'roomThree',
            title: 'Suite A',
            Suite: 'Suite A',
            titletext: 'Our Suite A offers breathtaking views of the city skyline',
            firstlisttext: 'Size: 235sq ft',
            secondlisttext: 'Beds: 2 Doubles(s)',
            roomSize: '235sq ft',
            bed: '2 Doubles(s)',
            icon: '/Images/i.png',
            icon1: '/Images/i0.png',
            icon2: '/Images/i1.png',
            icon3: '/Images/i2.png',
            icon4: '/Images/i3.png',
            icon5: '/Images/i4.png',
            icon6: '/Images/i5.png',
            price: '$225',
            buttontext: 'MORE INFO',
            link: '/suitethree'
        },
        {
            id:4,
            imgs: 'roomFour',
            title: 'Suite C',
            Suite: 'Suite C',
            titletext: 'Our Suite A offers breathtaking views of the city skyline',
            firstlisttext: 'Size: 220sq ft',
            secondlisttext: 'Beds: 1 king(s)',
            roomSize: '220sq ft',
            bed: '1 king(s)',
            icon: '/i.png',
            icon: '/Images/i.png',
            icon1: '/Images/i0.png',
            icon2: '/Images/i1.png',
            icon3: '/Images/i2.png',
            icon4: '/Images/i3.png',
            icon5: '/Images/i4.png',
            icon6: '/Images/i5.png',
            price: '$175',
            buttontext: 'MORE INFO',
            link: '/suitefour'
        },

        {
            id:5,
            imgs: 'roomFive',
            title: 'Suite A',
            Suite: 'Suite A',
            titletext: 'Our Suite A offers breathtaking views of the city skyline',
            firstlisttext: 'Size: 240sq ft',
            secondlisttext: 'Beds: 2 Doubles(s)',
            roomSize: '240sq ft',
            bed: '2 Doubles(s)',
            icon: '/Images/i.png',
            icon1: '/Images/i0.png',
            icon2: '/Images/i1.png',
            icon3: '/Images/i2.png',
            icon4: '/Images/i3.png',
            icon5: '/Images/i4.png',
            icon6: '/Images/i5.png',
            price: '$225',
            buttontext: 'MORE INFO',
            link: '/suitefive'
        },

        {
            id:6,
            imgs: 'roomSix',
            title: 'Suite B',
            Suite: 'Suite B',
            titletext: 'Our Suite A offers breathtaking views of the city skyline',
            firstlisttext: 'Size: 240sq ft',
            secondlisttext: 'Beds: 1 king(s)',
            roomSize: '235sq ft',
            bed: '1 king(s)',
            icon: '/Images/i.png',
            icon1: '/Images/i0.png',
            icon2: '/Images/i1.png',
            icon3: '/Images/i2.png',
            icon4: '/Images/i3.png',
            icon5: '/Images/i4.png',
            icon6: '/Images/i5.png',
            price: '$200',
            buttontext: 'MORE INFO',
            link: '/suitesix'
        }
    
]